// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wrap.CrazyEmoji.Api.Data;

#nullable disable

namespace Wrap.CrazyEmoji.Api.Data.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "aal_level", new[] { "aal1", "aal2", "aal3" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "code_challenge_method", new[] { "s256", "plain" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "factor_status", new[] { "unverified", "verified" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "factor_type", new[] { "totp", "webauthn", "phone" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_authorization_status", new[] { "pending", "approved", "denied", "expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_client_type", new[] { "public", "confidential" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_registration_type", new[] { "dynamic", "manual" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_response_type", new[] { "code" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "one_time_token_type", new[] { "confirmation_token", "reauthentication_token", "recovery_token", "email_change_token_new", "email_change_token_current", "phone_change_token" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "realtime", "action", new[] { "INSERT", "UPDATE", "DELETE", "TRUNCATE", "ERROR" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "realtime", "equality_op", new[] { "eq", "neq", "lt", "lte", "gt", "gte", "in" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "storage", "buckettype", new[] { "STANDARD", "ANALYTICS", "VECTOR" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "pg_stat_statements");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "uuid-ossp");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "graphql", "pg_graphql");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vault", "supabase_vault");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wrap.CrazyEmoji.Api.Data.Entities.ActiveRoom", b =>
                {
                    b.Property<string>("RoomCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<int>("CurrentRound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("EmojisSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("EmojisSentTime")
                        .HasColumnType("timestamp");

                    b.Property<bool>("GameStarted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("RoomCreator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("RoundDuration")
                        .HasColumnType("integer");

                    b.Property<bool>("RoundEnded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("RoundWord")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rounds")
                        .HasColumnType("integer");

                    b.HasKey("RoomCode")
                        .HasName("ActiveRooms_pkey");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RoomCreator");

                    b.ToTable("ActiveRooms");
                });

            modelBuilder.Entity("Wrap.CrazyEmoji.Api.Data.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Wrap.CrazyEmoji.Api.Data.Entities.RoomMember", b =>
                {
                    b.Property<string>("RoomCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("Username")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("GameScore")
                        .HasColumnType("bigint");

                    b.Property<bool>("GuessedRight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("GuessedWord")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasDefaultValueSql("'Player'::character varying");

                    b.HasKey("RoomCode", "Username")
                        .HasName("RoomMembers_pkey");

                    b.HasIndex("Username");

                    b.ToTable("RoomMembers");
                });

            modelBuilder.Entity("Wrap.CrazyEmoji.Api.Data.Entities.User", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connectionId");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Username")
                        .HasName("User_pkey");

                    b.HasIndex(new[] { "ConnectionId" }, "User_connectionId_key")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("Wrap.CrazyEmoji.Api.Data.Entities.Word", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Wrap.CrazyEmoji.Api.Data.Entities.ActiveRoom", b =>
                {
                    b.HasOne("Wrap.CrazyEmoji.Api.Data.Entities.Category", "CategoryNavigation")
                        .WithMany("ActiveRooms")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Wrap.CrazyEmoji.Api.Data.Entities.User", "RoomCreatorNavigation")
                        .WithMany("ActiveRooms")
                        .HasForeignKey("RoomCreator")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkUserCreator");

                    b.Navigation("CategoryNavigation");

                    b.Navigation("RoomCreatorNavigation");
                });

            modelBuilder.Entity("Wrap.CrazyEmoji.Api.Data.Entities.RoomMember", b =>
                {
                    b.HasOne("Wrap.CrazyEmoji.Api.Data.Entities.ActiveRoom", "RoomCodeNavigation")
                        .WithMany("RoomMembers")
                        .HasForeignKey("RoomCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkRoomMember");

                    b.HasOne("Wrap.CrazyEmoji.Api.Data.Entities.User", "UsernameNavigation")
                        .WithMany("RoomMembers")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkUserMember");

                    b.Navigation("RoomCodeNavigation");

                    b.Navigation("UsernameNavigation");
                });

            modelBuilder.Entity("Wrap.CrazyEmoji.Api.Data.Entities.Word", b =>
                {
                    b.HasOne("Wrap.CrazyEmoji.Api.Data.Entities.Category", "Category")
                        .WithMany("Words")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Wrap.CrazyEmoji.Api.Data.Entities.ActiveRoom", b =>
                {
                    b.Navigation("RoomMembers");
                });

            modelBuilder.Entity("Wrap.CrazyEmoji.Api.Data.Entities.Category", b =>
                {
                    b.Navigation("ActiveRooms");

                    b.Navigation("Words");
                });

            modelBuilder.Entity("Wrap.CrazyEmoji.Api.Data.Entities.User", b =>
                {
                    b.Navigation("ActiveRooms");

                    b.Navigation("RoomMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
